# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance_Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance_Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('main_service_capacity', models.IntegerField(default=0)),
                ('insolation', models.IntegerField(default=0)),
                ('monthly_electricity_usage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roof_type', models.CharField(choices=[('Asphalt', 'Asphalt'), ('Corrugated', 'Corrugated'), ('Tile', 'Tile')], default='Asphalt', max_length=200)),
                ('roof_height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roof_slope', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roof_area', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('credit_card_no', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('expiration_date', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('confirmation_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receptacle_Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Receptacle_Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roof_Mount_Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Roof_Mount_Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_size', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cable_length', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roof_peg_type', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('smartbox_size', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.House')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appliance_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Appliance_Installation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Payment_Method')),
                ('receptacle_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Receptacle_Installation')),
                ('roof_mount_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Roof_Mount_Installation')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.System')),
            ],
        ),
        migrations.AddField(
            model_name='roof_mount_installation',
            name='roof_mount_installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Roof_Mount_Installer'),
        ),
        migrations.AddField(
            model_name='receptacle_installation',
            name='receptacle_installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Receptacle_Installer'),
        ),
        migrations.AddField(
            model_name='appliance_installation',
            name='appliance_installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Appliance_Installer'),
        ),
        migrations.AddField(
            model_name='appliance_installation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Customer'),
        ),
    ]
