# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
    ]
