# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_availability',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptacle_installer_availability',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
