# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20161208_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='receptacle_installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.Receptacle_Installer'),
        ),
    ]
