# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_remove_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(blank='True', max_length=200),
        ),
    ]
