# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_house_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
    ]
