# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_auto_20161201_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='your_current_electricity_provider',
            field=models.CharField(choices=[('PG&E', 'PG&E'), ('SF Clean Energy', 'SF Clean Energy'), ('Other', 'Other')], default='PGE', max_length=200),
        ),
    ]
