# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20161212_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance_installer',
            old_name='roof_installer_pic',
            new_name='appliance_installer_pic',
        ),
    ]
