# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_auto_20161201_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='roof_area',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=9),
        ),
    ]
