# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0011_auto_20161201_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='roof_height',
        ),
        migrations.AlterField(
            model_name='house',
            name='stories',
            field=models.IntegerField(default=1),
        ),
    ]
