# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0012_auto_20161205_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='roof_slope',
        ),
        migrations.AddField(
            model_name='house',
            name='max_roof_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
