# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0014_auto_20161207_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='cable_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='desired_system_capacity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
