# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0015_auto_20161207_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='max_electrical_system_capacity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='house',
            name='number_of_modules',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='house',
            name='smartbox_size',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='house',
            name='system_capacity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
