# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0016_auto_20161207_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='max_electrical_system_capacity',
            new_name='max_electrical_system_capacity_amps',
        ),
        migrations.AddField(
            model_name='house',
            name='max_electrical_system_capacity_kW',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
