# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0017_auto_20161207_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='system_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
