# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0018_house_system_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='percent_of_electric_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='house',
            name='system_production',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='house',
            name='system_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
